INSERT INTO   STUDENT ( FIRST_NAME ,  LAST_NAME , AGE , GENDER ) VALUES( 'Jhon','Doe',25,'M');
INSERT INTO   STUDENT ( FIRST_NAME ,  LAST_NAME , AGE , GENDER ) VALUES( 'Stephen','Walf',25,'M');
INSERT INTO   STUDENT ( FIRST_NAME ,  LAST_NAME , AGE , GENDER ) VALUES( 'Joshua','Tim',25,'M');

INSERT INTO   TEACHER ( FIRST_NAME ,  LAST_NAME , AGE , GENDER ) VALUES( 'Daniel','Darwin',25,'M');
INSERT INTO   TEACHER ( FIRST_NAME ,  LAST_NAME , AGE , GENDER ) VALUES( 'Todd','Jim',25,'M');
INSERT INTO   TEACHER ( FIRST_NAME ,  LAST_NAME , AGE , GENDER ) VALUES( 'Samuel','Chris',25,'M');